apiVersion: v1
kind: Service
metadata:
  name: react
  namespace: money-honey
  labels:
    app: react
    component: frontend
    part-of: money-honey
spec:
  type: ClusterIP
  selector:
    app: react
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
