apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: money-honey
  labels:
    app: fastapi
    component: backend
    part-of: money-honey
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
